import Accordion from '../ui/Accordion.astro';
import Button from '../ui/Button.astro';
import Card from '../ui/Card.astro';
import H1 from '../ui/H1.astro';
import H2 from '../ui/H2.astro';
import H3 from '../ui/H3.astro';
import H4 from '../ui/H4.astro';
import Icon from '../ui/Icon.astro';
import Iframe from '../ui/Iframe.astro';
import Image from '../ui/Image.astro';
import Scroller from '../ui/Scroller.astro';
import Section from '../ui/Section.astro';
import Swiper from '../ui/Swiper/index.astro';
import Swiper_Slide from '../ui/Swiper/Slide.astro';
import WpNav from '../ui/WpNav.astro';
export { Accordion, Button, Card, H1, H2, H3, H4, Icon, Iframe, Image, Scroller, Section, Swiper, Swiper_Slide, WpNav };